# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_active', '0002_auto_20171223_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_active',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User_active',
        ),
    ]
