# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='art_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='art_title',
            new_name='title',
        ),
    ]
