# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171127_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='block_id',
            new_name='block',
        ),
    ]
