# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_active', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='User_active',
        ),
    ]
