# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_auto_20171203_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.CharField(max_length=10000, verbose_name='文章内容')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='板块索引')),
            ],
        ),
    ]
